version: '3.7'
services:
  openldap:
    image: osixia/openldap:latest
    container_name: ldap.docker
    hostname: ldap.docker
    ports: 
      - "389:389"
      - "636:636"
    volumes:
      - ./data/certificates:/container/service/slapd/assets/certs
      - ./data/slapd/database:/var/lib/ldap
      - ./data/slapd/config:/etc/ldap/slapd.d
    environment: 
      - LDAP_ORGANISATION=ramhlocal
      - LDAP_DOMAIN=ramhlocal.com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin_pass
      - LDAP_CONFIG_PASSWORD=config_pass
      - "LDAP_BASE_DN=dc=ramhlocal,dc=com"
      - LDAP_TLS_CRT_FILENAME=server.crt
      - LDAP_TLS_KEY_FILENAME=server.key
      - LDAP_TLS_CA_CRT_FILENAME=ramhlocal.com.ca.crt
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=user-ro
      - LDAP_READONLY_USER_PASSWORD=ro_pass
    networks:
      - testnet
  
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin.docker
    hostname: phpldapadmin.docker
    ports: 
      - "8081:80"
    environment: 
      - PHPLDAPADMIN_LDAP_HOSTS=ldap.docker
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - testnet

networks:
  testnet:
    driver: bridge
    external: true
# version: '2'
# services:
#   openldap:
#     image: osixia/openldap:1.5.0
#     container_name: ldap.docker
#     environment:
#       LDAP_LOG_LEVEL: "256"
#       LDAP_ORGANISATION: "Example Inc."
#       LDAP_DOMAIN: "example.org"
#       LDAP_BASE_DN: ""
#       LDAP_ADMIN_PASSWORD: "admin"
#       LDAP_CONFIG_PASSWORD: "config"
#       LDAP_READONLY_USER: "false"
#       #LDAP_READONLY_USER_USERNAME: "readonly"
#       #LDAP_READONLY_USER_PASSWORD: "readonly"
#       LDAP_RFC2307BIS_SCHEMA: "false"
#       LDAP_BACKEND: "mdb"
#       LDAP_TLS: "true"
#       LDAP_TLS_CRT_FILENAME: "ldap.crt"
#       LDAP_TLS_KEY_FILENAME: "ldap.key"
#       LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
#       LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
#       LDAP_TLS_ENFORCE: "false"
#       LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
#       LDAP_TLS_VERIFY_CLIENT: "demand"
#       LDAP_REPLICATION: "false"
#       #LDAP_REPLICATION_CONFIG_SYNCPROV: 'binddn="cn=admin,cn=config" bindmethod=simple credentials="$$LDAP_CONFIG_PASSWORD" searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical'
#       #LDAP_REPLICATION_DB_SYNCPROV: 'binddn="cn=admin,$$LDAP_BASE_DN" bindmethod=simple credentials="$$LDAP_ADMIN_PASSWORD" searchbase="$$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical'
#       #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
#       KEEP_EXISTING_CONFIG: "false"
#       LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
#       LDAP_SSL_HELPER_PREFIX: "ldap"
#     tty: true
#     stdin_open: true
#     volumes:
#       - /var/lib/ldap
#       - /etc/ldap/slapd.d
#       - /container/service/slapd/assets/certs/
#     ports:
#       - "389:389"
#       - "636:636"
#     # For replication to work correctly, domainname and hostname must be
#     # set correctly so that "hostname"."domainname" equates to the
#     # fully-qualified domain name for the host.
#     domainname: "ldap.docker"
#     hostname: "ldap-server"
#     networks:
#       - testnet
#   phpldapadmin:
#     image: osixia/phpldapadmin:latest
#     container_name: phpldapadmin
#     environment:
#       PHPLDAPADMIN_LDAP_HOSTS: "openldap"
#       PHPLDAPADMIN_HTTPS: "false"
#     ports:
#       - "8888:80"
#     depends_on:
#       - openldap
#     networks:
#       - testnet

# networks:
#   testnet:
#     driver: bridge
#     external: true