version: '3.8'
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:12.0.4
    environment:
      DB_VENDOR: h2
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_STATISTICS: all
      KEYCLOAK_LOGLEVEL: INFO
      JAVA_OPTS_APPEND: "-Dkeycloak.profile.feature.upload_script=enabled -Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.profile.feature.account2=enabled -Dkeycloak.profile.feature.account_api=enabled"
    ports:
      - 8080:8080
    networks:
      - testnet

networks:
  testnet:
    external: true